-record(buy, { market_name, contract_name, user, quantity, max_price }).
-record(sell, { market_name, contract_name, user, quantity, min_price }).
-record(create_contract, { market_name, contract_name, user, description }).
-record(create_market, { market_name, user, description }).
-record(open_market, { market_name, user }).
-record(close_market, { market_name, user }).